version: "3"
services:
    mongodb:
        image: mongo:latest
        container_name: "desafio_bd"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null

    backend:
        image: node:6.11.3
        container_name: desafio
        volumes:
            - .:/backend
            - /node_modules
        ports:
            - 8000:8000
        command: bash -c "cd /backend && node_modules/.bin/nodemon"


